### ISSUE TITLE
tfswitch step does not working anymore

### ISSUE THREAD

**Issue by padok-runner** [padok-team/github-workflows#32]
![image](https://github.com/padok-team/github-workflows/assets/94383822/116b99c4-dac1-4755-bffa-c92098ec69cc)

Ma CI/CD ne fonctionne plus sans aucun changement

```
name: Terraform quality

on: push

jobs:
  terraform-quality:
    uses: padok-team/github-workflows/.github/workflows/terraform-quality.yml@v1
    with:
      workdir: ./starters/terraform/layers
```
