### ISSUE TITLE
terragrunt quality check failed because of hard coded path

### ISSUE THREAD

**Issue by nlevee** [padok-team/github-workflows#49]
The action doesn't take care about the workdir variables for the steps :

```yaml
      - name: terraform fmt of directory modules
        run: terraform fmt -check -recursive -diff modules
      - name: terragrunt fmt of directory layers
        run: terragrunt hclfmt --terragrunt-check --terragrunt-diff layers
```
