### ISSUE TITLE
Some feedbacks on the current lint action

### ISSUE THREAD

**Issue by dixneuf19** [padok-team/github-workflows#5]
I think that the `ref:` part is not useful, it automatically fetch the current ref I believe.

```yaml
  - name: checkout
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
      ref: ${{ github.event.pull_request.head.ref }}
 ```
 
 There is no action to setup it ? Anyway, downloading the "latest", without fixing it may be a bit "dangerous", while useful (auto update, wow). I am quite mixed about this.
 
 
 ```yaml
- name: tfswitch
run: |
  wget https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh
  chmod 755 install.sh
  ./install.sh -b `pwd`/.bin
  rm install.sh
  CUSTOMBIN=`pwd`/.bin
  export PATH=$PATH:$CUSTOMBIN
  $CUSTOMBIN/tfswitch -b $CUSTOMBIN/terraform
  terraform -v
 ```

I personally don't like action which commits on the same place as human, I prefer only "blocking the PR". Indeed, if you want to iterate again on this PR, you'll have to `git pull` with the added commit from the workflow. This can be discussed

```yaml
- name: terraform-docs
  uses: terraform-docs/gh-actions@v1.0.0
  with:
    working-dir: .
    output-file: README.md
    output-method: inject
    git-commit-message: "docs: update terraform docs"
    git-push: "true"
```

More generally, I find this workflow OK for a module, but it would not function for a repo with layers, such as starters. 

For example for a project I had a pattern such as

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
    # needs a matrix to run it on all layers
      matrix:
        layer:
          - bootstrap
          - preprod-mybarnes
          - preprod-network
          - shared

    defaults:
      run:
        working-directory: terraform/layers/${{ matrix.layer }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
```

It was not ideal since the layers list is static, but It might be a interesting use case. Does github remote workflows supports this kind of specific usage (custom workdir based on a matrix, dynamic matrix) ?
